// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdm8r1wWmRKQNOnGUQ1swRdHpVrx4b80E',
    appId: '1:730985418594:web:3dba2441ef1ef4500ca63b',
    messagingSenderId: '730985418594',
    projectId: 'savingmoney-1779f',
    authDomain: 'savingmoney-1779f.firebaseapp.com',
    storageBucket: 'savingmoney-1779f.firebasestorage.app',
    measurementId: 'G-GVZP2HXJMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl36Vx0wdO1go5Kfjp5Xzeyi3aadg2oAo',
    appId: '1:730985418594:android:b37a4abcf37438040ca63b',
    messagingSenderId: '730985418594',
    projectId: 'savingmoney-1779f',
    storageBucket: 'savingmoney-1779f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd5qf5aJHOzB6qZEzydM7UBYtYUBCFkq0',
    appId: '1:730985418594:ios:f1828c7457668cf50ca63b',
    messagingSenderId: '730985418594',
    projectId: 'savingmoney-1779f',
    storageBucket: 'savingmoney-1779f.firebasestorage.app',
    iosBundleId: 'com.example.savingmoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd5qf5aJHOzB6qZEzydM7UBYtYUBCFkq0',
    appId: '1:730985418594:ios:f1828c7457668cf50ca63b',
    messagingSenderId: '730985418594',
    projectId: 'savingmoney-1779f',
    storageBucket: 'savingmoney-1779f.firebasestorage.app',
    iosBundleId: 'com.example.savingmoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdm8r1wWmRKQNOnGUQ1swRdHpVrx4b80E',
    appId: '1:730985418594:web:43c1719ee08d43850ca63b',
    messagingSenderId: '730985418594',
    projectId: 'savingmoney-1779f',
    authDomain: 'savingmoney-1779f.firebaseapp.com',
    storageBucket: 'savingmoney-1779f.firebasestorage.app',
    measurementId: 'G-0MSGSV6FHD',
  );
}
